### ISSUE TITLE
Setup Mac

### ISSUE THREAD

**Issue by findthebug** [kelly/flipdisc-server#1]
This project looks promising so i try to get startet here.

My Configuration:
- OSX 15.0.1
- Python 3.10.15
- Node v22.11.0

Dependencies installation went well. 

To get startet i just use the base server setup and configured one panel like this: 

Layout
```javascript
const layout = [
  [1,2]
]
const devices = [{
  path: '/dev/tty.usbserial-B002DP2A',
  addresses: [1, 2],
  baudRate: 57600
}]
const options = {
  isMirrored: true
}
export { layout, devices, options }
 ```
Server
```javascript
import { Display, createServer } from 'flipdisc-server'
import { layout, devices, options } from './config/config.js'

Display.configure(layout, devices, options)
const app = createServer()
 ```
Scenes:
To test i use 2 scenes like this: (test1 and test2) located in scenes folder
```javascript
import { createScene, ImageView } from 'flipdisc-server'

const defaults = {
  url: 'http://server.local:3000/eink1/images/sweden3.png',
}

const schema = {
  title: 'Image',
  description: 'test 1',
  properties: {
    url: {
      type: 'string',
      default: defaults.url,
    },
  }
}
 
const image = async function(options) {
  options = { ...defaults, ...options };
  const { url } = options;
  const scene = new createScene();
  let img
   
  scene.once('loaded', async () => {
    img = new ImageView(url)
    img.fitWidth()
    scene.add(img)
  })

  return scene;
}

export { image as scene, schema }
```

if i call: http://localhost:3000/api/scenes i get this, which looks valid
```javascript
[{"title":"Image","description":"displaying an image","properties":{"url":{"type":"string","default":"http://server.local:3000/eink1/images/sweden3.png"}},"id":0},{"title":"Image","description":"test 2","properties":{"url":{"type":"string","default":"http://server.local:3000/eink1/images/sweden2.png"}},"id":1}] 
```

As soon as i try to get the scene with api i get internal server error back:

```javascript
home@macbookAirM3 ~ % curl -X GET http://localhost:3000/api/scenes/1 (or 0)
Internal Server Error%     
```

```javascript
Opened USB device: /dev/tty.usbserial-B002DP2A baud rate: 57600
TypeError: Cannot read properties of undefined (reading 'id')
    at Array.getSceneByID (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/flipdisc-server/src/api/scene.js:11:32)
    at #dispatch (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/hono/dist/hono-base.js:182:38)
    at fetch (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/hono/dist/hono-base.js:208:26)
    at Server.<anonymous> (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/@hono/node-server/dist/index.mjs:412:13)
    at Server.emit (node:events:518:28)
    at parserOnIncoming (node:_http_server:1150:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
```

I get the same error if i use:
http://localhost:3000/api/scenes/next

Is there a minimal server example you could provide just to test the base setup and APIs?

**Comment by kelly** [comment]
Should be fixed if you get the latest. /next requires you to first add an item to a queue. If you want to start playing the first scene, you can just POST to http://localhost:3000/api/playing
