### ISSUE TITLE
iOS App

### ISSUE THREAD

**Issue by findthebug** [kelly/flipdisc-server#2]
Since the base server is running and shows an image, i was up to test the iOS App;

```javascript
home@macbookAirM3 flipdisc-server % node server.js
(node:47911) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
{"level":30,"time":1731750440641,"pid":47911,"hostname":"macbookAirM3.fritz.box","msg":"Listening on http://localhost:3000"}
Opened USB device: /dev/tty.usbserial-B002DP2A baud rate: 57600
```

looks valid and image shows up.

as soon as i try to connect with iOS App i get this message

```javascript
TypeError: Cannot read properties of undefined (reading 'length')
    at Module.packBits (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/flipdisc/src/utils.js:49:27)
    at get content (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/flipdisc/src/panels/alfazeta.js:34:18)
    at get content (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/flipdisc/src/display.js:286:48)
    at get info (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/flipdisc/src/display.js:326:7)
    at Array.getDisplay (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/flipdisc-server/src/api/display.js:5:25)
    at #dispatch (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/hono/dist/hono-base.js:182:38)
    at fetch (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/hono/dist/hono-base.js:208:26)
    at Server.<anonymous> (file:///Users/home/Daten/projects/dot-display/flipdisc-server/node_modules/@hono/node-server/dist/index.mjs:412:13)
    at Server.emit (node:events:518:28)
    at parserOnIncoming (node:_http_server:1150:12)
```

![Bildschirmfoto 2024-11-16 um 10 48 45](https://github.com/user-attachments/assets/e5d00c11-0fec-4315-8a8d-dff0a4190663)

**Comment by kelly** [comment]
I think this issue is due to you not entering a websocket address. Right now it's just deployed on the same server: "macbookAirM3.local:7071". Let me know if that fixes the issue. You'll probably have to disconnect and fill in all the information again.

**Comment by kelly** [comment]
I fixed an issue in the flipdisc npm module. If you pull the latest, it should work. Thanks!

**Comment by findthebug** [comment]
Get now this:
```javascript
{"level":30,"time":1731839527448,"pid":24434,"hostname":"macbookAirM3.fritz.box","msg":"Listening on http://localhost:3000"}
Opened USB device: /dev/tty.usbserial-B002DP2A baud rate: 57600
TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
    at get content (file:///Users/home/Downloads/test/node_modules/flipdisc/src/display.js:286:22)
    at get info (file:///Users/home/Downloads/test/node_modules/flipdisc/src/display.js:326:7)
    at Array.getDisplay (file:///Users/home/Downloads/test/src/api/display.js:5:25)
    at #dispatch (file:///Users/home/Downloads/test/node_modules/hono/dist/hono-base.js:182:38)
    at fetch (file:///Users/home/Downloads/test/node_modules/hono/dist/hono-base.js:208:26)
    at Server.<anonymous> (file:///Users/home/Downloads/test/node_modules/@hono/node-server/dist/index.mjs:412:13)
    at Server.emit (node:events:518:28)
    at parserOnIncoming (node:_http_server:1150:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)

**Comment by kelly** [comment]
Should be fixed with the latest version. 🤞
